# Project: Project
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o sec_main.o
LINKOBJ  = main.o sec_main.o
LIBS     = -L"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/lib" -L"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/include" -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/include" -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"F:/APPLICATION/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = F:\APPLICATION\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

sec_main.o: sec_main.cpp
	$(CPP) -c sec_main.cpp -o sec_main.o $(CXXFLAGS)
